BUILD-1

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -1,48 +1,43 @@
-name: CI-CD
+name: Build and Deploy Android App
 
 on:
   push:
-    branches: [main]
-  pull_request:
-    branches: [main]
-  schedule:
-    - cron: '0 0 1,15 * *'
+    branches: [ main ]
 
 jobs:
   build:
     runs-on: ubuntu-latest
 
     steps:
-      - name: Checkout code
-        uses: actions/checkout@v2
+      - uses: actions/checkout@v2
 
-      - name: Get Date
-        id: get-date
+      - name: Install required tools
+        uses: mox/setup-android-sdk@v1
+        with:
+          sdk_root: <path/to/sdk>
+          ndk_version: <ndk_version> # Optional
+          packages:
+            - build-tools;35.0.0-rc1 # Replace with your version if needed
+
+      - name: Check build-tools folder
         run: |
-          echo "::set-output name=date::$(/bin/date -u "+%Y%m%d")"
-        shell: bash
+          if [ ! -d "$ANDROID_HOME/build-tools" ]; then
+            echo "Build-tools folder not found. Please install required tools."
+            exit 1
+          fi
+
+      - name: Install Buildozer
+        run: pip install buildozer
+
+      - name: Update buildozer.spec
+        run: |
+          echo 'android.sdk_tools_version = 35.0.0-rc1' >> buildozer.spec 
 
       - name: Cache Buildozer global directory
-        uses: actions/cache@v2
+        uses: actions/cache@v3
         with:
           path: .buildozer_global
-          key: buildozer-global-${{ hashFiles('buildozer.spec') }}
-
-      - uses: actions/cache@v2
-        with:
-          path: .buildozer
-          key: ${{ runner.os }}-${{ steps.get-date.outputs.date }}-${{ hashFiles('buildozer.spec') }}
-
-      - name: Install Android SDK
-        run: |
-          sudo apt-get update
-          sudo apt-get install -y openjdk-8-jdk
-          wget https://dl.google.com/android/repository/commandlinetools-linux-7302050_latest.zip -O sdk-tools.zip
-          unzip -qq sdk-tools.zip -d $HOME/android-sdk
-          echo "export ANDROID_HOME=$HOME/android-sdk" >> $HOME/.bashrc
-          echo "export PATH=$PATH:$ANDROID_HOME/tools:$ANDROID_HOME/tools/bin:$ANDROID_HOME/platform-tools" >> $HOME/.bashrc
-          source $HOME/.bashrc
-          yes | sdkmanager --licenses
+          key: ${{ runner.os }}-buildozer-${{ hashFiles('buildozer.spec') }}
 
       - name: Build with Buildozer
         uses: ArtemSBulgakov/buildozer-action@v1
